### ISSUE TITLE
Use of slug for entry_filename_pattern seems to lowercase input

### ISSUE THREAD

**Issue by Andersos** [contentful/contentful-metalsmith#50]
So when I try to use `entry_filename_pattern: ${ sys.id }` it looks like all the filnames are lowercased even thoguht the `sys.id`'s might have uppercase characters in them. So I am seeing problems when trying to access content with ids in the url.

It looks like it is picking up the data [here](https://github.com/contentful/contentful-metalsmith/blob/master/lib/util.js#L91) then using the internal function _slug that again is calling [slug-component](https://github.com/contentful/contentful-metalsmith/blob/master/lib/util.js#L22).

The documentation is outdated since it is referencing another slug library [here](https://github.com/contentful/contentful-metalsmith/blame/master/docs/source-file-settings.md#L141).

Trying to track down the slug library used here [shows that the `toLowerCase()` function](https://github.com/yields/slug/blob/master/index.js#L22) is hardcoded so there is no way to pass in an option to not lowercase the string.

**Comment by manubaum** [comment]
+1
